"""Exact occurrence probabilities for GGS ``random_setup(14)`` starts.

The input directory ``records321_14_random_setup`` contains one spatial
representative for each position that the primary GGS r14 generator can
produce.  This module restores the probability mass which was lost when the
generator enumerated only one representative for each of the eight rotations
and reflections.

For 14 discs, the generator always occupies the central four squares and
chooses ten of the next twelve squares.  It chooses the number of white discs
from 5 through 9 uniformly, then chooses their locations uniformly.  Thus an
oriented board with ``k`` white discs has probability

    1 / (C(12, 10) * 5 * C(14, k)).

The stored representative stands for every distinct spatial orientation of
that board, so its probability is that value multiplied by its orbit size.
All arithmetic uses :class:`fractions.Fraction`; no floating-point ordering is
used to decide which positions are calculated first.
"""

from __future__ import annotations

import argparse
import functools
import hashlib
import json
import os
import uuid
from collections import Counter
from fractions import Fraction
from math import comb
from pathlib import Path
from typing import Any, Iterable

from build_book import canonicalize_board_key, transform_board_text
from othello import normalize_board_text


R14_RANDOM_SETUP_PROBABILITY_SCHEMA = "ggs_random_setup_14_probability_v1"
R14_RANDOM_SETUP_PRIORITY_ROW_SCHEMA = "ggs_random_setup_14_priority_row_v1"
R14_RANDOM_SETUP_PRIORITY_MANIFEST_SCHEMA = "ggs_random_setup_14_priority_manifest_v1"
R14_DISCS = 14
R14_CENTRAL_CELL_COUNT = 4
R14_NEXT_RING_CELL_COUNT = 12
R14_NEXT_RING_SELECTED_COUNT = 10
R14_SILHOUETTE_COUNT = comb(R14_NEXT_RING_CELL_COUNT, R14_NEXT_RING_SELECTED_COUNT)
R14_WHITE_COUNTS = tuple(range(5, 10))
R14_WHITE_COUNT_CHOICES = len(R14_WHITE_COUNTS)

# This literal is recorded by teacher generation when probability ordering is
# selected.  Keeping it as structured data makes a later audit independent of
# prose wording and of a floating-point implementation.
R14_RANDOM_SETUP_PROBABILITY_MODEL: dict[str, object] = {
    "schema": R14_RANDOM_SETUP_PROBABILITY_SCHEMA,
    "n_discs": R14_DISCS,
    "central_cell_count": R14_CENTRAL_CELL_COUNT,
    "next_ring_cell_count": R14_NEXT_RING_CELL_COUNT,
    "next_ring_selected_count": R14_NEXT_RING_SELECTED_COUNT,
    "silhouette_count": R14_SILHOUETTE_COUNT,
    "white_disc_counts": list(R14_WHITE_COUNTS),
    "white_count_choices": R14_WHITE_COUNT_CHOICES,
    "oriented_board_probability": "1 / (C(12,10) * 5 * C(14,k))",
    "representative_probability": "orbit_size / (C(12,10) * 5 * C(14,k))",
    "spatial_transformations": 8,
}


def _ring_distance(index: int) -> int:
    """Match the distance formula used by ``random_setup.cpp`` exactly."""
    x = index % 8
    y = index // 8
    return (max(abs(2 * x - 7), abs(2 * y - 7)) - 1) // 2


@functools.lru_cache(maxsize=262_144)
def validate_r14_random_setup_board(board: str) -> str:
    """Normalize and validate one position generated by ``random_setup(14)``.

    Validation is deliberately strict: applying this model to a board from a
    different GGS random-start algorithm would silently produce a misleading
    priority order.
    """
    normalized = normalize_board_text(board)
    cells = normalized[:64]
    side = normalized[65]
    if side != "X":
        raise ValueError("random_setup(14) must have X to move")
    if sum(cell != "-" for cell in cells) != R14_DISCS:
        raise ValueError("random_setup(14) must contain exactly 14 discs")
    white_discs = cells.count("O")
    if white_discs not in R14_WHITE_COUNTS:
        raise ValueError(
            "random_setup(14) must contain one of "
            f"{R14_WHITE_COUNTS} white-disc counts, got {white_discs}"
        )

    central = 0
    next_ring = 0
    for index, cell in enumerate(cells):
        distance = _ring_distance(index)
        if distance == 0:
            if cell == "-":
                raise ValueError("random_setup(14) is missing a central disc")
            central += 1
        elif distance == 1:
            if cell != "-":
                next_ring += 1
        elif cell != "-":
            raise ValueError("random_setup(14) has a disc outside its selectable ring")
    if central != R14_CENTRAL_CELL_COUNT or next_ring != R14_NEXT_RING_SELECTED_COUNT:
        raise ValueError("random_setup(14) has an unexpected occupied-cell silhouette")
    return normalized


@functools.lru_cache(maxsize=262_144)
def r14_random_setup_orbit_size(board: str) -> int:
    """Return the number of distinct rotations/reflections of ``board``."""
    normalized = validate_r14_random_setup_board(board)
    return len({transform_board_text(normalized, symmetry) for symmetry in range(8)})


@functools.lru_cache(maxsize=262_144)
def r14_random_setup_probability(board: str) -> Fraction:
    """Return the exact probability mass represented by a stored r14 root."""
    normalized = validate_r14_random_setup_board(board)
    white_discs = normalized[:64].count("O")
    return Fraction(
        r14_random_setup_orbit_size(normalized),
        R14_SILHOUETTE_COUNT * R14_WHITE_COUNT_CHOICES * comb(R14_DISCS, white_discs),
    )


def _tie_break_key(board: str, tie_seed: int | None) -> bytes | str:
    if tie_seed is None:
        return board
    return hashlib.sha256(f"{tie_seed}\0{board}".encode("ascii")).digest()


def order_r14_random_setup_boards(
    boards: Iterable[str], tie_seed: int | None = None
) -> list[str]:
    """Order unique r14 starts by decreasing exact GGS generation probability.

    A supplied ``tie_seed`` affects only positions having exactly the same
    probability.  It therefore diversifies a bounded initial calculation
    without changing the priority between positions of different probability.
    """
    normalized = sorted({validate_r14_random_setup_board(board) for board in boards})
    return sorted(
        normalized,
        key=lambda board: (
            -r14_random_setup_probability(board),
            _tie_break_key(board, tie_seed),
            board,
        ),
    )


def fraction_json(value: Fraction) -> dict[str, int]:
    """Serialize an exact rational value without rounding it."""
    return {"numerator": value.numerator, "denominator": value.denominator}


def ordered_boards_sha256(boards: Iterable[str]) -> str:
    digest = hashlib.sha256()
    for board in boards:
        digest.update(board.encode("ascii"))
        digest.update(b"\n")
    return digest.hexdigest()


def priority_manifest_metadata_path(path: Path) -> Path:
    """Return the immutable sidecar metadata path for one priority file."""
    return path.with_suffix(path.suffix + ".meta.json")


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    try:
        temporary.write_text(text, encoding="utf-8", newline="\n")
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def priority_rows(boards: Iterable[str], tie_seed: int | None) -> tuple[list[str], list[dict[str, Any]]]:
    """Build the ordered, self-checking rows used by a frozen priority file."""
    ordered = order_r14_random_setup_boards(boards, tie_seed)
    rows: list[dict[str, Any]] = []
    for rank, board in enumerate(ordered, start=1):
        rows.append(
            {
                "schema": R14_RANDOM_SETUP_PRIORITY_ROW_SCHEMA,
                "rank": rank,
                "board": board,
                "white_discs": board[:64].count("O"),
                "orbit_size": r14_random_setup_orbit_size(board),
                "probability": fraction_json(r14_random_setup_probability(board)),
            }
        )
    return ordered, rows


def write_r14_random_setup_priority_manifest(
    path: Path,
    audit: dict[str, Any],
    boards: Iterable[str],
    tie_seed: int | None,
) -> dict[str, Any]:
    """Write and return a complete, immutable probability-priority input file.

    The JSON Lines file stores every ranked position and its exact rational
    probability.  Its sidecar JSON records the hash of that file and the input
    audit.  A teacher run reads this file rather than recomputing an order from
    whichever Python version happens to be installed at resume time.
    """
    resolved = path.resolve()
    ordered, rows = priority_rows(boards, tie_seed)
    payload = "".join(
        json.dumps(row, ensure_ascii=True, sort_keys=True, separators=(",", ":")) + "\n"
        for row in rows
    )
    _atomic_write_text(resolved, payload)
    output_fingerprint = {
        "path": resolved.as_posix(),
        "sha256": _sha256_file(resolved),
        "bytes": resolved.stat().st_size,
        "rows": len(rows),
    }
    metadata = {
        "schema": R14_RANDOM_SETUP_PRIORITY_MANIFEST_SCHEMA,
        "row_schema": R14_RANDOM_SETUP_PRIORITY_ROW_SCHEMA,
        "model": R14_RANDOM_SETUP_PROBABILITY_MODEL,
        "tie_seed": tie_seed,
        "input_audit": {
            "schema": audit["schema"],
            "start_directory": audit["start_directory"],
            "source_files": audit["source_files"],
            "rows": audit["rows"],
            "unique_canonical_rows": audit["unique_canonical_rows"],
            "total_probability": audit["total_probability"],
        },
        "output": output_fingerprint,
        "ordered_roots_sha256": ordered_boards_sha256(ordered),
    }
    _atomic_write_text(
        priority_manifest_metadata_path(resolved),
        json.dumps(metadata, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
    )
    return metadata


def _read_json(path: Path, label: str) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read {label} {path}: {error}") from error
    if not isinstance(value, dict):
        raise ValueError(f"{label} {path} is not a JSON object")
    return value


def load_r14_random_setup_priority_manifest(path: Path) -> tuple[list[str], dict[str, Any]]:
    """Load and fully validate a previously frozen r14 priority file.

    File hashes establish byte identity, but they cannot establish that a
    newly supplied file was generated in probability order.  This loader also
    recomputes the complete order from each row and the recorded tie seed.
    """
    resolved = path.resolve()
    metadata_path = priority_manifest_metadata_path(resolved)
    metadata = _read_json(metadata_path, "priority metadata")
    if metadata.get("schema") != R14_RANDOM_SETUP_PRIORITY_MANIFEST_SCHEMA:
        raise ValueError("priority metadata has an unsupported schema")
    if metadata.get("row_schema") != R14_RANDOM_SETUP_PRIORITY_ROW_SCHEMA:
        raise ValueError("priority metadata has an unexpected row schema")
    if metadata.get("model") != R14_RANDOM_SETUP_PROBABILITY_MODEL:
        raise ValueError("priority metadata has an unexpected probability model")
    tie_seed = metadata.get("tie_seed")
    if tie_seed is not None and (isinstance(tie_seed, bool) or not isinstance(tie_seed, int)):
        raise ValueError("priority metadata has an invalid tie seed")
    output = metadata.get("output")
    if not isinstance(output, dict):
        raise ValueError("priority metadata has no output fingerprint")
    if output.get("path") != resolved.as_posix():
        raise ValueError("priority metadata has an unexpected output path")
    if output.get("sha256") != _sha256_file(resolved):
        raise ValueError("priority file does not match its recorded SHA-256")
    if output.get("bytes") != resolved.stat().st_size:
        raise ValueError("priority file does not match its recorded byte count")

    boards: list[str] = []
    try:
        lines = resolved.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError) as error:
        raise ValueError(f"cannot read priority file {resolved}: {error}") from error
    for line_number, line in enumerate(lines, start=1):
        try:
            row = json.loads(line)
        except json.JSONDecodeError as error:
            raise ValueError(f"{resolved}:{line_number}: invalid JSON row: {error}") from error
        if not isinstance(row, dict) or row.get("schema") != R14_RANDOM_SETUP_PRIORITY_ROW_SCHEMA:
            raise ValueError(f"{resolved}:{line_number}: unsupported priority row")
        if row.get("rank") != line_number:
            raise ValueError(f"{resolved}:{line_number}: non-contiguous priority rank")
        board = row.get("board")
        if not isinstance(board, str):
            raise ValueError(f"{resolved}:{line_number}: no board")
        board = validate_r14_random_setup_board(board)
        canonical, _ = canonicalize_board_key(board)
        if board != canonical:
            raise ValueError(f"{resolved}:{line_number}: board is not a spatial representative")
        expected_probability = fraction_json(r14_random_setup_probability(board))
        if (
            row.get("white_discs") != board[:64].count("O")
            or row.get("orbit_size") != r14_random_setup_orbit_size(board)
            or row.get("probability") != expected_probability
        ):
            raise ValueError(f"{resolved}:{line_number}: probability details do not match the board")
        boards.append(board)
    if output.get("rows") != len(boards) or not boards:
        raise ValueError("priority metadata has an unexpected row count")
    if len(boards) != len(set(boards)):
        raise ValueError("priority file contains duplicate boards")
    if metadata.get("ordered_roots_sha256") != ordered_boards_sha256(boards):
        raise ValueError("priority file does not match its recorded ordered-root SHA-256")
    if boards != order_r14_random_setup_boards(boards, tie_seed):
        raise ValueError("priority file is not in its recorded probability order")
    return boards, metadata


def priority_manifest_provenance(path: Path) -> dict[str, object]:
    """Return immutable fingerprints after validating a priority file."""
    boards, metadata = load_r14_random_setup_priority_manifest(path)
    resolved = path.resolve()
    metadata_path = priority_manifest_metadata_path(resolved)
    return {
        "path": resolved.as_posix(),
        "sha256": _sha256_file(resolved),
        "bytes": resolved.stat().st_size,
        "metadata_path": metadata_path.as_posix(),
        "metadata_sha256": _sha256_file(metadata_path),
        "rows": len(boards),
        "ordered_roots_sha256": metadata["ordered_roots_sha256"],
    }


def audit_r14_random_setup_directory(start_dir: Path, tie_seed: int | None = 620) -> dict[str, Any]:
    """Audit a complete r14 primary-generator directory and its priority order."""
    files = sorted(start_dir.resolve().glob("*.txt"), key=lambda path: path.as_posix())
    if not files:
        raise ValueError(f"{start_dir}: no .txt position files")

    rows: list[str] = []
    canonical_rows: list[str] = []
    source_files: list[dict[str, object]] = []
    for path in files:
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeError) as error:
            raise ValueError(f"cannot read {path}: {error}") from error
        count = 0
        for line_number, line in enumerate(lines, start=1):
            if not line.strip():
                continue
            try:
                board = validate_r14_random_setup_board(line)
            except ValueError as error:
                raise ValueError(f"{path}:{line_number}: {error}") from error
            rows.append(board)
            canonical, _ = canonicalize_board_key(board)
            canonical_rows.append(canonical)
            count += 1
        source_files.append(
            {
                "path": path.as_posix(),
                "bytes": path.stat().st_size,
                "sha256": _sha256_file(path),
                "rows": count,
            }
        )

    if len(rows) != len(set(rows)):
        raise ValueError("the r14 input has exact duplicate rows")
    if len(canonical_rows) != len(set(canonical_rows)):
        raise ValueError("the r14 input has rotation/reflection duplicate rows")
    if any(board != canonical for board, canonical in zip(rows, canonical_rows)):
        raise ValueError("the r14 input contains a non-representative orientation")

    ordered = order_r14_random_setup_boards(rows, tie_seed)
    total_probability = sum(
        (r14_random_setup_probability(board) for board in ordered), Fraction(0)
    )
    if total_probability != 1:
        raise ValueError(
            "the r14 input does not cover the full random_setup(14) probability mass: "
            f"{total_probability}"
        )

    by_white_count: Counter[int] = Counter()
    by_orbit_size: Counter[int] = Counter()
    probability_by_white_count: dict[int, Fraction] = {}
    probability_by_orbit_size: dict[int, Fraction] = {}
    for board in ordered:
        white_discs = board[:64].count("O")
        orbit_size = r14_random_setup_orbit_size(board)
        probability = r14_random_setup_probability(board)
        by_white_count[white_discs] += 1
        by_orbit_size[orbit_size] += 1
        probability_by_white_count[white_discs] = (
            probability_by_white_count.get(white_discs, Fraction(0)) + probability
        )
        probability_by_orbit_size[orbit_size] = (
            probability_by_orbit_size.get(orbit_size, Fraction(0)) + probability
        )

    checkpoints = sorted(
        {
            count
            for count in (100, 500, 1_000, 5_000, 10_000, 25_000, 50_000, 100_000, len(ordered))
            if count <= len(ordered)
        }
    )
    cumulative = Fraction(0)
    checkpoint_mass: dict[str, dict[str, int]] = {}
    checkpoint_iter = iter(checkpoints)
    next_checkpoint = next(checkpoint_iter, None)
    for index, board in enumerate(ordered, start=1):
        cumulative += r14_random_setup_probability(board)
        if index == next_checkpoint:
            checkpoint_mass[str(index)] = fraction_json(cumulative)
            next_checkpoint = next(checkpoint_iter, None)

    return {
        "schema": R14_RANDOM_SETUP_PROBABILITY_SCHEMA,
        "model": R14_RANDOM_SETUP_PROBABILITY_MODEL,
        "start_directory": start_dir.resolve().as_posix(),
        "source_files": source_files,
        "rows": len(rows),
        "unique_canonical_rows": len(set(canonical_rows)),
        "tie_seed": tie_seed,
        "ordered_roots_sha256": ordered_boards_sha256(ordered),
        "total_probability": fraction_json(total_probability),
        "counts_by_white_discs": {str(key): value for key, value in sorted(by_white_count.items())},
        "probability_by_white_discs": {
            str(key): fraction_json(value)
            for key, value in sorted(probability_by_white_count.items())
        },
        "counts_by_orbit_size": {str(key): value for key, value in sorted(by_orbit_size.items())},
        "probability_by_orbit_size": {
            str(key): fraction_json(value)
            for key, value in sorted(probability_by_orbit_size.items())
        },
        "cumulative_probability_by_calculation_count": checkpoint_mass,
    }


def _atomic_write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    try:
        temporary.write_text(
            json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def main() -> int:
    from config import START_DIR

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--start-dir", type=Path, default=START_DIR)
    parser.add_argument("--tie-seed", type=int, default=620)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--priority-output",
        type=Path,
        help="Write every ranked board and exact probability as a frozen JSON Lines input",
    )
    args = parser.parse_args()
    report = audit_r14_random_setup_directory(args.start_dir, args.tie_seed)
    _atomic_write_json(args.output, report)
    if args.priority_output is not None:
        metadata = write_r14_random_setup_priority_manifest(
            args.priority_output,
            report,
            order_r14_random_setup_boards(
                [
                    line
                    for path in sorted(args.start_dir.resolve().glob("*.txt"))
                    for line in path.read_text(encoding="utf-8").splitlines()
                    if line.strip()
                ],
                args.tie_seed,
            ),
            args.tie_seed,
        )
        print(
            f"wrote r14 priority manifest with {metadata['output']['rows']} roots; "
            f"sha256={metadata['output']['sha256']}"
        )
    print(
        f"wrote r14 probability audit for {report['rows']} roots; "
        f"ordered_roots_sha256={report['ordered_roots_sha256']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
